package com.team_abnormals.environmental.core.other;

import java.awt.Color;
import java.util.List;

import com.team_abnormals.environmental.common.entity.ButterflyEntity.Variant;

public enum ButterflyType {
    //TIGER(new Variant("Orange Tiger", new Color(), new Color()), new Variant("Yellow Tiger", new Color(), new Color()), new Variant("Dark Glassy Tiger", new Color(), new Color()), new Variant("Blue Glassy Tiger", new Color(), new Color())),
    //MONARCH(new Variant("Orange Monarch", new Color(), new Color()), new Variant("Yellow Monarch", new Color(), new Color()), new Variant("Pale Monarch", new Color(), new Color())),
    //CABBAGE(new Variant("White Cabbage", new Color(), new Color()), new Variant("Yellow Cabbage", new Color(), new Color())),
    //SKIPPER(new Variant("Arctic Skipper", new Color(), new Color()), new Variant("Sandhill Skipper", new Color(), new Color()), new Variant("Fiery Skipper", new Color(), new Color()), new Variant("Northern White Skipper", new Color(), new Color()), new Variant("Silver-Spotted  Skipper", new Color(), new Color()), new Variant("Woodland Skipper", new Color(), new Color()), new Variant("Coconut  Skipper", new Color(), new Color()), new Variant("Banana  Skipper", new Color(), new Color())),
    //COPPER(new Variant("Copper", new Color(), new Color()), new Variant("Blue Copper", new Color(), new Color()), new Variant("Desert Tailed Copper", new Color(), new Color()), new Variant("Gorgon Copper", new Color(), new Color()), new Variant("Great Copper", new Color(), new Color()), new Variant("Lustrous Copper", new Color(), new Color()), new Variant("Purplish Copper", new Color(), new Color()), new Variant("Snowy Copper", new Color(), new Color())),
    //SWALLOWTAIL(new Variant("Swallowtail", new Color(), new Color()), new Variant("Western Tiger Swallowtail", new Color(), new Color()), new Variant("Pale Swallowtail", new Color(), new Color()), new Variant("Pipevine Swallowtail", new Color(), new Color()), new Variant("Black Swallowtail", new Color(), new Color()), new Variant("Zebra Swallowtail", new Color(), new Color())),
    //SULPHUR(new Variant("Sulphur", new Color(), new Color()), new Variant("Cloudless Sulphur", new Color(), new Color()), new Variant("Dainty Sulphur", new Color(), new Color()), new Variant("Orange Sulphur", new Color(), new Color()), new Variant("Yellow Sulphur", new Color(), new Color())),
    //DOG_FACE(new Variant("Dog-Face", new Color(), new Color())),
    //LONGWING(new Variant("Longwing", new Color(), new Color())),
    //PEARLY_EYE(new Variant("Southern Pearly-Eye", new Color(), new Color()), new Variant("Northern Pearly-Eye", new Color(), new Color())),
    //BANNER(new Variant("Banner", new Color(), new Color()), new Variant("Orange Banner", new Color(), new Color())),
    //NYPMH(new Variant("Nymph", new Color(), new Color())),
    //ADMIRAL(new Variant("Admiral", new Color(), new Color()), new Variant("Red Admiral", new Color(), new Color()), new Variant("White Admiral", new Color(), new Color())),
    //BUCKEYE(new Variant("Buckeye", new Color(), new Color()), new Variant("Tropical Buckeye", new Color(), new Color()), new Variant("Mangrove Buckeye", new Color(), new Color())),
    //HAIRSTREAK(new Variant("Bramble Hairstreak", new Color(), new Color()), new Variant("Golden Hairstreak", new Color(), new Color()), new Variant("Golden Oak Hairstreak", new Color(), new Color()), new Variant("Gray Hairstreak", new Color(), new Color()), new Variant("Great Purple Hairstreak", new Color(), new Color()), new Variant("Juniper Hairstreak", new Color(), new Color()), new Variant("Green Hairstreak", new Color(), new Color()), new Variant("Mahogany Hairstreak", new Color(), new Color()), new Variant("Sepia Hairstreak", new Color(), new Color()), new Variant("Thicket Hairstreak", new Color(), new Color()), new Variant("Willow Hairstreak", new Color(), new Color()), new Variant("Black Hairstreak", new Color(), new Color())),
    //GATEKEEPER(new Variant("Gatekeeper", new Color(), new Color())),
    //GRAYLING(new Variant("Grayling", new Color(), new Color())),
    //MOURNING_CLOAK(new Variant("Mourning Cloak", new Color(), new Color())),
    //FRITALLARY(new Variant("Dark Green Fritallary", new Color(), new Color()), new Variant("Heath Fritallary", new Color(), new Color()), new Variant("High Brown Fritallary", new Color(), new Color()), new Variant("Marsh Fritallary", new Color(), new Color()), new Variant("Pearl Fritallary", new Color(), new Color()), new Variant("Silver Fritallary", new Color(), new Color()), new Variant("Gulf Fritallary", new Color(), new Color()), new Variant("Spangled Fritallary", new Color(), new Color()), new Variant("Atlantis Fritallary", new Color(), new Color()), new Variant("Mountain Fritallary", new Color(), new Color()), new Variant("Meadow Fritallary", new Color(), new Color()), new Variant("Regal Fritallary", new Color(), new Color()), new Variant("Polaris Fritallary", new Color(), new Color()), new Variant("Cryptic Fritallary", new Color(), new Color())),
    //RINGLET(new Variant("Ringlet", new Color(), new Color()), new Variant("Mountain Ringlet", new Color(), new Color())),
    //ARGUS(new Variant("Argus", new Color(), new Color()), new Variant("Northern Brown Argus", new Color(), new Color())),
    //EMPEROR(new Variant("Emperor", new Color(), new Color()), new Variant("Purple Emperor", new Color(), new Color()), new Variant("Hackberry Emperor", new Color(), new Color()), new Variant("Tawny Emperor", new Color(), new Color()), new Variant("Silver Emperor", new Color(), new Color()), new Variant("Dusky Emperor", new Color(), new Color())),
    //CLOUDY(new Variant("Cloudy", new Color(), new Color()), new Variant("Yellow Cloudy", new Color(), new Color())),
    //DUSKY(new Variant("Dreamy Dusky", new Color(), new Color()), new Variant("Mournful Dusky", new Color(), new Color()), new Variant("Sad Dusky", new Color(), new Color()), new Variant("Sleepy Dusky", new Color(), new Color())),
    //SOOTY(new Variant("Sooty", new Color(), new Color())),
    //PYGMY(new Variant("Pygmy", new Color(), new Color()), new Variant("Blue Pygmy", new Color(), new Color())),
    //ARROWHEAD(new Variant("Arrowhead", new Color(), new Color()), new Variant("Blue Arrowhead", new Color(), new Color())),
    //GOSSAMER(new Variant("Gossamer", new Color(), new Color()), new Variant("Sooty Gossamer", new Color(), new Color())),
    //AZURE(new Variant("Azure", new Color(), new Color()), new Variant("Spring Azure", new Color(), new Color())),
    //ELFIN(new Variant("Elfin", new Color(), new Color()), new Variant("Moss Elfin", new Color(), new Color()), new Variant("Western Pine Elfin", new Color(), new Color()), new Variant("Western Brown Elfin", new Color(), new Color())),
    //PARNASSIAN(new Variant("Parnassian", new Color(), new Color())),
    //MARBLE(new Variant("Gray Marble", new Color(), new Color())),
    //PATCH(new Variant("Patch", new Color(), new Color()), new Variant("Bordered Patch", new Color(), new Color()), new Variant("Crimson Patch", new Color(), new Color())),
    //CRESCENT(new Variant("Crescent", new Color(), new Color()), new Variant("Feather River Crescent", new Color(), new Color()), new Variant("Pearl Crescent", new Color(), new Color()), new Variant("Black Crescent", new Color(), new Color()), new Variant("Pine Crescent", new Color(), new Color()), new Variant("Chestnut Crescent", new Color(), new Color()), new Variant("Field Crescent", new Color(), new Color()), new Variant("Pale Crescent", new Color(), new Color())),
    //TORTOISESHELL(new Variant("Tortoiseshell", new Color(), new Color())),
    //CHECKERSPOT(new Variant("Northern Checkerspot", new Color(), new Color()), new Variant("Arachne Checkerspot", new Color(), new Color()), new Variant("Black Checkerspot", new Color(), new Color()), new Variant("Silvery Checkerspot", new Color(), new Color())),
    //COMMA(new Variant("Comma", new Color(), new Color()), new Variant("Green Comma", new Color(), new Color()), new Variant("Gray Comma", new Color(), new Color())),
    //SATYR(new Variant("Ox-Eyed Satyr", new Color(), new Color()), new Variant("Anglewing Satyr", new Color(), new Color()), new Variant("Canyonland Satyr", new Color(), new Color()), new Variant("Red Satyr", new Color(), new Color()), new Variant("Pine Satyr", new Color(), new Color()), new Variant("White Satyr", new Color(), new Color())),
    //QUEEN(new Variant("Queen", new Color(), new Color())),
    //SILVERSPOT(new Variant("Silverspot", new Color(), new Color())),
    //SISTER(new Variant("Eyed Sister", new Color(), new Color()), new Variant("Rayed Sister", new Color(), new Color())),
    //MORPHO(new Variant("White Morpho", new Color(), new Color())),
    //COMMODORE(new Variant("Commodore", new Color(), new Color())),
    //LACEWING(new Variant("Lacewing", new Color(), new Color()), new Variant("Malay Lacewing", new Color(), new Color()), new Variant("Leopard Lacewing", new Color(), new Color())),
    //APOLLO(new Variant("Apollo", new Color(), new Color())),
    //SHOEMAKER(new Variant("Shoemaker", new Color(), new Color())),
    //FESTOON(new Variant("Festoon", new Color(), new Color())),
    //JEWEL(new Variant("Jewel", new Color(), new Color()), new Variant("Western Jewel", new Color(), new Color()), new Variant("Bulloak Jewel", new Color(), new Color())),
    //MIMIC(new Variant("Mimic", new Color(), new Color())),
    //BEAUTY(new Variant("Beauty", new Color(), new Color())),
    //CHALKHILL(new Variant("Chalkhill", new Color(), new Color())),
    //METALMARK(new Variant("Metalmark", new Color(), new Color())),
    //ORANGETIP(new Variant("Orangetip", new Color(), new Color()), new Variant("Great Orangetip", new Color(), new Color())),
    //HELICONIAN(new Variant("Heliconian", new Color(), new Color())),
    //DAGGERWING(new Variant("Daggerwing", new Color(), new Color()), new Variant("Waiter Daggerwing", new Color(), new Color()), new Variant("Ruddy Daggerwing", new Color(), new Color())),
    //VICEROY(new Variant("Viceroy", new Color(), new Color())),
    //MALACHITE(new Variant("Malachite", new Color(), new Color())),
    //PAGE(new Variant("Page", new Color(), new Color())),
    //WALL(new Variant("Wall", new Color(), new Color())),
    //MEADOW(new Variant("Meadow", new Color(), new Color())),
    //OWLET(new Variant("Owlet", new Color(), new Color()), new Variant("Orange Owlet", new Color(), new Color())),
    //SNOUT(new Variant("Snout", new Color(), new Color())),
    //EYED(new Variant("Eyed", new Color(), new Color())),
    //DASH(new Variant("Dash", new Color(), new Color())),
    //HARVESTER(new Variant("Harvester", new Color(), new Color())),
    //BRIMSTONE(new Variant("Brimstone", new Color(), new Color())),
    //QUESTION_MARK(new Variant("Question Mark", new Color(), new Color())),
    //ADONIS(new Variant("Adonis", new Color(), new Color())),
    //SUNSET(new Variant("Sunset", new Color(), new Color())),
    //POSTMAN(new Variant("Postman", new Color(), new Color())),
    //DUKE(new Variant("Purple Duke", new Color(), new Color())),
    //GLASSWING(new Variant("Glasswing", new Color(), new Color())),
    //ROSE(new Variant("Rose", new Color(), new Color())),
    //CHECKERED(new Variant("Checkered", new Color(), new Color())),
    //SPICEBUSH(new Variant("Spicebush", new Color(), new Color())),
    //HEATH(new Variant("Heath", new Color(), new Color())),
    //HOLLY(new Variant("Holly", new Color(), new Color())),
    //PEACOCK(new Variant("Peacock", new Color(), new Color()), new Variant("White Peacock", new Color(), new Color()), new Variant("Banded Peacock", new Color(), new Color())),
    //CLOUDLESS(new Variant("Cloudless", new Color(), new Color())),
    //LEAFWING(new Variant("Leafwing", new Color(), new Color()), new Variant("Angled Leafwing", new Color(), new Color()), new Variant("Pointed Leafwing", new Color(), new Color()), new Variant("Tropical Leafwing", new Color(), new Color()), new Variant("Goatweed Leafwing", new Color(), new Color()), new Variant("Pale-Spotted Leafwing", new Color(), new Color())),
    //CLEARWING(new Variant("Clearwing", new Color(), new Color())),
    //EDGE(new Variant("Edge", new Color(), new Color())),
    //LADY(new Variant("West Coast Lady", new Color(), new Color()), new Variant("Painted Lady", new Color(), new Color())),
    //ALPINE(new Variant("Alpine", new Color(), new Color()), new Variant("Taiga Alpine", new Color(), new Color()), new Variant("Reddish Alpine", new Color(), new Color()), new Variant("Eskimo Alpine", new Color(), new Color()), new Variant("Banded Alpine", new Color(), new Color())),
    //ARCTIC(new Variant("Arctic", new Color(), new Color()), new Variant("Great Arctic", new Color(), new Color()), new Variant("Arctic Sentinel", new Color(), new Color()), new Variant("Early Arctic", new Color(), new Color())),
    //SILVERLINE(new Variant("Silverline", new Color(), new Color())),
    //SPRITE(new Variant("Sprite", new Color(), new Color())),
    //VIRGIN(new Variant("Virgin", new Color(), new Color())),
    //BIRDWING(new Variant("Birdwing", new Color(), new Color())),
    //MIME(new Variant("Mime", new Color(), new Color())),
    //HELEN(new Variant("Helen", new Color(), new Color()), new Variant("Great Helen", new Color(), new Color()), new Variant("Blue Helen", new Color(), new Color())),
    //MORMON(new Variant("Mormon", new Color(), new Color()), new Variant("Great Mormon", new Color(), new Color())),
    //BLUEBOTTLE(new Variant("Bluebottle", new Color(), new Color())),
    //JAY(new Variant("Jay", new Color(), new Color()), new Variant("Blue Jay", new Color(), new Color()), new Variant("Tailed Jay", new Color(), new Color())),
    //SWORDTAIL(new Variant("Swordtail", new Color(), new Color())),
    //JEZEBEL(new Variant("Jezebel", new Color(), new Color()), new Variant("Red Jezebel", new Color(), new Color()), new Variant("Painted Jezebel", new Color(), new Color())),
    //PSYCHE(new Variant("Psyche", new Color(), new Color())),
    //ALBATROSS(new Variant("Albatross", new Color(), new Color()), new Variant("Chocolate Albatross", new Color(), new Color()), new Variant("Striped Albatross", new Color(), new Color())),
    //EMIGRANT(new Variant("Emigrant", new Color(), new Color()), new Variant("Mottled Emigrant", new Color(), new Color()), new Variant("Orange Emigrant", new Color(), new Color())),
    //CROW(new Variant("Black Crow", new Color(), new Color()), new Variant("Malayan Crow", new Color(), new Color()), new Variant("Blue Crow", new Color(), new Color()), new Variant("King Crow", new Color(), new Color()), new Variant("Dwarf Crow", new Color(), new Color()), new Variant("Magpie Crow", new Color(), new Color())),
    //PALMFLY(new Variant("Palmfly", new Color(), new Color()), new Variant("Tawny Palmfly", new Color(), new Color()), new Variant("Pointed Palmfly", new Color(), new Color())),
    //RING(new Variant("Ring", new Color(), new Color())),
    //FAUN(new Variant("Faun", new Color(), new Color())),
    //KING(new Variant("King", new Color(), new Color()), new Variant("Palm King", new Color(), new Color())),
    //SATURN(new Variant("Saturn", new Color(), new Color())),
    //GLORY(new Variant("Glory", new Color(), new Color()), new Variant("Dark Blue Glory", new Color(), new Color())),
    //DUFFER(new Variant("Duffer", new Color(), new Color())),
    //EGGFLY(new Variant("Malayan Eggfly", new Color(), new Color()), new Variant("Great Eggfly", new Color(), new Color())),
    //PANSY(new Variant("Pansy", new Color(), new Color()), new Variant("Chocolate Pansy", new Color(), new Color()), new Variant("Peacock Pansy", new Color(), new Color()), new Variant("Gray Pansy", new Color(), new Color()), new Variant("Blue Pansy", new Color(), new Color())),
    //LEOPARD(new Variant("Leopard", new Color(), new Color())),
    //ASSYRIAN(new Variant("Royal Assyrian", new Color(), new Color())),
    //CRUISER(new Variant("Cruiser", new Color(), new Color())),
    //RUSTIC(new Variant("Rustic", new Color(), new Color())),
    //YEOMAN(new Variant("Yeoman", new Color(), new Color())),
    //COMMANDER(new Variant("Commander", new Color(), new Color())),
    //KNIGHT(new Variant("Knight", new Color(), new Color())),
    //SERGEANT(new Variant("Sergeant", new Color(), new Color()), new Variant("Lance Sergeant", new Color(), new Color()), new Variant("Studded Sergeant", new Color(), new Color()), new Variant("Color Sergeant", new Color(), new Color())),
    //SAILOR(new Variant("Sailor", new Color(), new Color()), new Variant("Blue-Eyed Sailor", new Color(), new Color()), new Variant("Gray Sailor", new Color(), new Color()), new Variant("Chocolate Sailor", new Color(), new Color())),
    //CRACKER(new Variant("Cracker", new Color(), new Color()), new Variant("Red Cracker", new Color(), new Color()), new Variant("Gray Cracker", new Color(), new Color()), new Variant("Pale Cracker", new Color(), new Color())),
    //LASCAR(new Variant("Lascar", new Color(), new Color())),
    //VISCOUNT(new Variant("Viscount", new Color(), new Color())),
    //BARON(new Variant("Baron", new Color(), new Color()), new Variant("Malay Baron", new Color(), new Color()), new Variant("White-Tipped Baron", new Color(), new Color()), new Variant("Green Baron", new Color(), new Color())),
    //ARCHDUKE(new Variant("Archduke", new Color(), new Color())),
    //MAPLET(new Variant("Little Maplet", new Color(), new Color())),
    //COURTESAN(new Variant("Courtesan", new Color(), new Color())),
    //NAWAB(new Variant("Nawab", new Color(), new Color()), new Variant("Blue Nawab", new Color(), new Color())),
    //RAJAH(new Variant("Rajah", new Color(), new Color()), new Variant("Black Rajah", new Color(), new Color())),
    //HARLEQUIN(new Variant("Harlequin", new Color(), new Color()), new Variant("Lesser Harlequin", new Color(), new Color())),
    //APEFLY(new Variant("Apefly", new Color(), new Color())),
    //SUNBEAM(new Variant("Sunbeam", new Color(), new Color()), new Variant("Malayan Sunbeam", new Color(), new Color())),
    //DARKIE(new Variant("Darkie", new Color(), new Color())),
    //BROWNIE(new Variant("Brownie", new Color(), new Color())),
    //CUPID(new Variant("Cupid", new Color(), new Color()), new Variant("Indian Cupid", new Color(), new Color())),
    //PIERROT(new Variant("Peirrot", new Color(), new Color()), new Variant("Elbowed Pierrot", new Color(), new Color())),
    //QUAKER(new Variant("Quaker", new Color(), new Color())),
    //FORGET_ME_NOT(new Variant("Forget-Me-Not", new Color(), new Color()), new Variant("Silver Forget-Me-Not", new Color(), new Color())),
    //CAERULEAN(new Variant("Caerulean", new Color(), new Color()), new Variant("Dark Caerulean", new Color(), new Color()), new Variant("Metallic Caerulean", new Color(), new Color())),
    //IMPERIAL(new Variant("Imperial", new Color(), new Color()), new Variant("Branded Imperial", new Color(), new Color()), new Variant("Great Imperial", new Color(), new Color()), new Variant("Grand Imperial", new Color(), new Color()), new Variant("Green Imperial", new Color(), new Color())),
    //YAMFLY(new Variant("Yamfly", new Color(), new Color())),
    //POSY(new Variant("Posy", new Color(), new Color()), new Variant("Dark Posy", new Color(), new Color())),
    //ONYX(new Variant("Onyx", new Color(), new Color()), new Variant("Ambon Onyx", new Color(), new Color())),
    //ROYAL(new Variant("White Royal", new Color(), new Color()), new Variant("Royal Peacock", new Color(), new Color()), new Variant("Chocolate Royal", new Color(), new Color()), new Variant("Golden Royal", new Color(), new Color()), new Variant("Silver Royal", new Color(), new Color())),
    CORNELIAN(new Variant("Cornelian", new Color(153, 122, 102), new Color(203, 189, 179))),
    TIT(new Variant("Tit", new Color(230, 255, 255), new Color(179, 94, 0))),
    SPARK(new Variant("Spark", new Color(255, 255, 204), new Color(255, 204, 153))),
    PLANE(new Variant("Plane", new Color(176, 150, 0), new Color(40, 34, 0))),
    FLASH(new Variant("Slate Flash", new Color(102, 102, 255), new Color(153, 102, 255)), new Variant("Yellow Flash", new Color(255, 204, 102), new Color(72, 36, 0)), new Variant("Copper Flash", new Color(255, 197, 153), new Color(179, 104, 0)), new Variant("Red Flash", new Color(255, 57, 0), new Color(60, 19, 0))),
    FLAT(new Variant("Pied Flat", new Color(255, 138, 32), new Color(153, 102, 51)), new Variant("Snow Flat", new Color(28, 20, 15), new Color(230, 255, 255))),
    ANGLE(new Variant("Chestnut Angle", new Color(204, 153, 102), new Color(57, 39, 20))),
    BOB(new Variant("Chestnut Bob", new Color(255, 102, 0), new Color(255, 0, 0)), new Variant("Palm Bob", new Color(255, 230, 204), new Color(72, 36, 0))),
    COON(new Variant("Coon", new Color(255, 153, 51), new Color(255, 204, 102))),
    DEMON(new Variant("Grass Demon", new Color(75, 48, 22), new Color(223, 255, 255)), new Variant("Chocolate Demon", new Color(94, 39, 0), new Color(153, 102, 0))),
    FLITTER(new Variant("Flitter", new Color(72, 29, 0), new Color(255, 204, 153)), new Variant("Gold Flitter", new Color(255, 255, 102), new Color(128, 32, 0))),
    LANCER(new Variant("Chequered Lancer", new Color(43, 21, 0), new Color(255, 255, 174)), new Variant("Vein Lancer", new Color(98, 33, 11), new Color(255, 153, 0)), new Variant("Pugnacious Lancer", new Color(236, 159, 0), new Color(153, 102, 51))),
    REDEYE(new Variant("Redeye", new Color(196, 98, 0), new Color(153, 77, 0)), new Variant("Giant Redeye", new Color(89, 45, 0), new Color(204, 204, 255))),
    PALMER(new Variant("Palmer", new Color(255, 177, 100), new Color(155, 58, 0)), new Variant("Hoary Palmer", new Color(204, 153, 255), new Color(164, 102, 255))),
    BRUSHFOOT(new Variant("Brushfoot", new Color(204, 204, 255), new Color(255, 134, 0))),
    SWIFT(new Variant("Swift", new Color(255, 200, 100), new Color(225, 180, 0)), new Variant("Great Swift", new Color(205, 145, 0), new Color(205, 165, 0)), new Variant("Paintbrush Swift", new Color(128, 40, 0), new Color(24, 13, 38)));

    public static final ButterflyType[] types = values();
    public List<Variant> variants;

    ButterflyType(Variant... data) {
        for (Variant d : data) {
            variants.add(d);
        }
    }

    public List<Variant> getVariants() {
        return variants;
    }
}